### ISSUE TITLE
Transaction Yönetimi

### ISSUE THREAD

**Issue by guneysus** [TurgayCan2/EFGeneric#1]
Mobilden baktım da transaction yönetimi göremedim.

**Comment by TurgayCan2** [comment]
Generic içinde TM(Transaction management) ihtiyaç varmı?
 
Şahsi fikrim ve tecrübem derki;
TM yönetimi servis katmanında olmalı ve oluşabilecek data source'a bağlı exception'ların handle edilmeside bu katmanda yapılmalı.

**Comment by guneysus** [comment]
Evet, bazen Business, bazen de Servis katmanında yapılıyor. Fakat örnek bir iskelet yapısı elde bulunsa güzel olur diye söyledim. Benzer bir Repo, Unit of Work ve Business repository iskelet yapısını (Dependency Injection) patterni ile gerçek bir yazılım geliştirirken yazıyorum. Vaktim olduğunda, PR ile destek vermeye çalışırım.

**Comment by TurgayCan2** [comment]
Business diye ayrı bir katman mı var? .Net lügatına biraz yabancıyım , bu konuda junior biri olarak soruyorum sadece. Servis katmanı kapsam olarak business logic ve buna dair işler.. 

EFGeneric zaten DbContext(IEntityCotnext) ve domain'i(BaseEntity<T>, IDeletable, IVersionable gibi gibi..) tamamen soyutluyor ve istediğiniz gibi bu iki çatının arayüzleri üzerinde rahatça koşturmanıza olanak sağlıyor. İstediğiniz şekildede genişletme olanağı sunuyor.

Unit of work tasarım kalıbının yapacağı işi herhangi bir DI framework'ü yapabilmesi gerekiyor (TM için söylüyorum), daha derinlemesine araştırma yapmadım bu konuda (servis katmanı için belirleyeceğim DI framework bu konuda beni yönlendiriyor olacaktır ve farklı bir proje konusu aslında) lakin (Unit of work)gerekliliği yada benim düşündüğüm mimari içerisinde DAL'ı tekrar bir düğüme indirgemek ne kadar doğru bilemedim..

**Comment by guneysus** [comment]
Söylediğiniz konular aslında sadece .NET için değil, JAVA, C++ gibi diller için geçerli aslında.

Businees katmanı bildiğim ve anladığım kadarıyla projeye-şirkete özgü kontrolleri yapan (*validation* katman.

Ben de çok ileri seviye sayılmam ama daha önce gördüğüm, projenin ilk aşamasında, gerekmediği halde Business katmanı ile aynı işi yapan bir Servis katmanı konmuştu. Bunu frenkler *over-engineering*, *over-kill* gibi kelimeler ile tabir ediyorlar.

Aslında o mimaride, Businees katmanı TM'dan başka bir iş yapmıyordu yanlış hatırlamıyorsam. Kısacası,  lazım olur, ileride web-servisini bu katmandan sunarız diye konmuş olsa gerek :smile: 

Şu https://msdn.microsoft.com/en-us/library/bb384398.aspx adresten baktım da, kısacası, Servis ve Business katmanlarının 2'sinin bir arada olması çoğu durumda tamamen gereksiz gibi duruyor.

Yani sizin "Businees diye ayrı katman mı var?" sorunuz, benim "Servis diye ayrı katman mı var?" sorular aynı şeyler bence. 

Sadece katmanların isimlendirmelerinde fark var.

**Comment by TurgayCan2** [comment]
Lügat farkı aslında. Servis lügat olarak(java için konuşuyorum farklı dillerde farklı anlamlara gelebiliyor anladığım), kapsar {Business Logic, Data Source Exception Handling, Business Exception handling, I/O processing vs. vs..}

Business Logic Layer :) benim kafamda sadece iş mantığı dışında bir şey çağrıştırmıyor. Bana sorsan; kötü bir isimlendirme olmuş. Bana göre; Service çok daha kapsayıcı.. 

Yaklaşımlar farklı çoğu noktada farklı (bana göre kötü) lakin implementasyonu yapabildiğim sürece (EF tabanlı EFgeneric DAL projem bir örnek) sıkıntı değil. 

Java standartı ve yaklaşımıyla .Net yazmaya çabalıyorum ;)
